version: '3'
services:
  db:
    image: postgres:12.1
    container_name: graphql-practices-db
    restart: always
    # ports: 
    #   - "5432:5432"
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    networks:
      - "net"
    volumes:
      - "data:/var/lib/postgresql/data"
  prisma:
    image: prismagraphql/prisma:1.34
    container_name: graphql-practices-prisma
    restart: always
    ports:
      - "4466:4466"
    depends_on:
      - db
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: db
            database: $POSTGRES_DB
            user: $POSTGRES_USER
            password: $POSTGRES_PASSWORD
            ssl: false
            rawAccess: true
            port: '5432'
            migrations: true
      PRISMA_SECRET: $PRISMA_SECRET
    networks:
      - "net"
  server:
    image: node-graphql-practices
    build: 
      context: .
      dockerfile: Dockerfile.server
    container_name: graphql-practices-server
    restart: always
    command: ["npm", "run", "dev"]
    ports: 
      - "4000:4000"
    depends_on:
      - prisma
    env_file: .env
    networks:
      - "net"
    volumes:
      - ./:/opt/graphql-practices

networks:
  net:

volumes:
  data: