version: '3'
services:
  db:
    image: postgres:12.1
    container_name: graphql-practices-db
    restart: always
    # ports: 
    #   - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 1q2w3e4r5t6y
      POSTGRES_USER: user
      POSTGRES_DB: graphql-db
    networks:
      - "net"
    volumes:
      - "data:/var/lib/postgresql/data"
  prisma:
    image: prismagraphql/prisma:1.34
    container_name: graphql-practices-prisma
    restart: always
    ports:
      - "4466:4466"
    depends_on:
      - db
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: db
            database: graphql-db
            user: user
            password: 1q2w3e4r5t6y
            ssl: false
            rawAccess: true
            port: '5432'
            migrations: true
    networks:
      - "net"
  server:
    image: node-graphql-practices
    build: 
      context: .
      dockerfile: Dockerfile.server
    container_name: graphql-practices-server
    restart: always
    ports: 
      - "4000:4000"
    depends_on:
      - prisma
    environment:
      PRISMA_ENDPOINT: http://prisma:4466/
    networks:
      - "net"

networks:
  net:

volumes:
  data: