version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-227-251-33.compute-1.amazonaws.com
            database: dbr5isnofn2943
            user: mhoqnautruuksl
            password: 076590a7e788c65965806e166189d7522a2aa69970388afdada30cfacdb4b433
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true